project:
  type: website

website:
  title: "ISSS608"
  navbar:
    background: "#e0ae24"
    left:
    - text: "Syllabus"
      href: syllabus.html
    - text: "Lesson Plan"
      href: lesson.html
    - text: "Take-home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "TH_EX/TH_EX1.html"
        - text: "Take-home Exercise 2"
          href: "TH_EX/TH_EX2.html"
        - text: "Take-home Exercise 3"
          href: "TH_EX/TH_EX3.html"
    - text: "Visual Analytics Project"
      href: VAproject.html

    right:
    - text: "Tableau Resources"
      href: Tableau.html
    - text: "All About R"
      menu: 
        - text: "R Resouces"
          href: R.html
        - text: "R for Visual Analytics"
          href: R4Vis.html
        - text: "R tips & tricks"
          href: Rt.html
        - text: "Quarto"
          href: Quarto.html
        - text: "git and github"
          href: git.html
    - text: "Home"
      href: index.html

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

